sudo: required

# Install Docker
services:
  - docker

# Execute logic
script:
  - echo "Hello Students!"

after_success:
  # Build all the docker files
  - docker build -t abinsha/zomato-shapeai-client ./client
  - docker build -t abinsha/zomato-shapeai-server ./server
  - docker build -t abinsha/zomato-shapeai-nginx ./nginx

  # log in docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # push to docker hub
  - docker push abinsha/zomato-shapeai-client
  - docker push abinsha/zomato-shapeai-server
  - docker push abinsha/zomato-shapeai-nginx